// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jdzywzwivygnjjlfidgv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Impkenl3endpdnlnbmpqbGZpZGd2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAzMjE0MzYsImV4cCI6MjA2NTg5NzQzNn0.07w_aLXDqehaOlfTjnILiHlgocK-mVWZAaSiFnd-1g0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);